print("Logika AND")
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print("----------\n")
print("Logika OR")
print(True and True)
print(True and False)
print(False and True)
print(False and False)